# Generated by Django 5.0.3 on 2024-03-16 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_management', '0002_alter_device_device_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['serial_number']},
        ),
        migrations.AlterField(
            model_name='checkoutlog',
            name='return_condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
